version: '3.8'

services:
  web:
    container_name: web_server
    build:
      context: .
      dockerfile: app/Dockerfile
    #    command: gunicorn nextnovel.wsgi:application -w 3 -k gevent --bind 0.0.0.0:8000 --reload
    command: gunicorn nextnovel.wsgi:application -w 3 -k gevent --bind 0.0.0.0:8000 --reload --timeout=0
    ports:
      - 8000:8000
    env_file:
      - env_files/.env
    depends_on:
      - db
    volumes:
      ## for development only
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
  db:
    container_name: db_server
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env_files/.env.db
    ports:
      - "5432:5432"
  redis:
    build:
      context: .
      dockerfile: redis/Dockerfile
    container_name: redis_server
    ports:
      - "6379:6379"
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/conf/redis.conf
    depends_on:
      - web
  nginx:
    container_name: nginx_server
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

